# Generated by Django 2.2.7 on 2019-11-22 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcall',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='refill',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='refill',
            name='previous_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
    ]
