# Generated by Django 2.2.7 on 2019-11-22 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20191122_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashcall',
            options={'ordering': ['-date_deposited']},
        ),
        migrations.AlterModelOptions(
            name='refill',
            options={'ordering': ['-date_deposited']},
        ),
        migrations.RemoveField(
            model_name='cashcall',
            name='user_balance',
        ),
        migrations.AddField(
            model_name='cashcall',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='cashcall',
            name='previous_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
    ]
