# Generated by Django 2.2.7 on 2019-12-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191130_1330'),
        ('bank', '0003_auto_20191123_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcall',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserAddress'),
        ),
        migrations.AddField(
            model_name='refill',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserAddress'),
        ),
    ]
