# Generated by Django 3.0 on 2019-12-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['user'], 'verbose_name': 'user address', 'verbose_name_plural': 'user addresses'},
        ),
    ]
