# Generated by Django 2.2.7 on 2019-11-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191123_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'user address', 'verbose_name_plural': 'user addresses'},
        ),
    ]
